[package]
name = "dbx-mssql"
version.workspace = true
edition.workspace = true
license = "BSD-2-Clause"

[dependencies]
dbx-core = { path = "../dbx-core" }
async-trait.workspace = true
tokio.workspace = true
tiberius.workspace = true
tokio-util.workspace = true
futures-util.workspace = true
tracing.workspace = true
