[workspace]
resolver = "2"
members = ["crates/dbx", "crates/dbx-core", "crates/dbx-pg", "crates/dbx-mssql", "crates/dbx-ntlm", "crates/dbx-mysql"]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
tokio = { version = "1", features = ["full"] }
async-trait = "0.1"
thiserror = "2"
anyhow = "1"
clap = { version = "4", features = ["derive"] }
tokio-postgres = "0.7"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
colored = "2"
ipnet = "2"
indicatif = "0.17"
rusqlite = { version = "0.31", features = ["bundled"] }
dirs = "5"
tiberius = { version = "0.12", default-features = false, features = ["tds73", "rustls"] }
tokio-util = { version = "0.7", features = ["compat"] }
futures-util = "0.3"
md4 = "0.10"
md-5 = "0.10"
hmac = "0.12"
rand = "0.8"
mysql_async = { version = "0.34", default-features = false, features = ["minimal-rust"] }

[profile.release]
strip = true
lto = "thin"
codegen-units = 1
